name: tutter_radio
description: Trackies luisteren met de squad
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: 2.11.0
  web_ffi: 0.7.2
  opus_dart: 3.0.0
  opus_flutter_web: 3.0.1
  websafe_svg: 3.0.0+4
  url_launcher_web: 2.0.9
  protobuf: 2.1.0
  rxdart: 0.27.7
  web_socket_channel: 2.4.0
  http: 0.13.5
  shared_preferences: 2.1.0
  image: 4.0.15

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/danielsad.png
    - assets/dumbledoh.png
    - assets/ferris.svg
    - assets/flutter.svg
    - assets/github.svg
    - assets/tutter.png
    - assets/opus.svg
    - assets/tutterdj.jpg

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
